resources:
  - ../../../type/gating/phases
  - ../../../function/airshipctl-base-catalogues

patchesJson6902:
  - target:
      group: airshipit.org
      version: v1alpha1
      kind: Clusterctl
      name: "clusterctl_init"
    path: clusterctl-patch.yaml
  - target:
      group: airshipit.org
      version: v1alpha1
      kind: VersionsCatalogue
      name: "versions-airshipctl"
    path: clusterctl-image-patch.yaml

patchesStrategicMerge:
  - plan_patch.yaml

transformers:
  - ../../../function/clusterctl/replacements
  - ../../../phases/replacements
