apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../function/workers-capz/v0.5.2
  - ../../target/catalogues

namespace: target-infra

transformers:
  - ../../../../function/workers-capz/v0.5.2/replacements
