resources:
  - ../../../../composite/infra
  - ../../../../function/clusterctl
  - ../../../../function/airshipctl-catalogues
  - ../../../../function/baremetal-operator
patchesStrategicMerge:
  - patch_bmo_config.yaml
commonLabels:
  airshipit.org/stage: initinfra
transformers:
  - ../../../../function/baremetal-operator/replacements
