resources:
  - ../../../../composite/infra
  - ../../../../function/clusterctl
  - ../../../../function/airshipctl-catalogues
  - ../../../../function/baremetal-operator

patchesStrategicMerge:
  - patch_bmo_config.yaml

commonLabels:
  airshipit.org/stage: initinfra

generators:
  - ../../../../function/airshipctl-catalogues

transformers:
  - ../../../../function/baremetal-operator/replacements
