apiVersion: airshipit.org/v1alpha1
kind: VariableCatalogue
metadata:
  # NOTE: change this when copying this example
  name: hardwareprofile-example
  labels:
    airshipit.org/deploy-k8s: "false"

hardwareProfile:
  firmware:
    sriovEnabled: false
    virtualizationEnabled: false
    simultaneousMultithreadingEnabled: false
  raid:
    hardwareRAIDVolumes:
    - name: "VirtualDisk1"
      level: "0"
      sizeGibibytes: 2048
      numberOfPhysicalDisks: 2
      rotational: False
    - name: "VirtualDisk2"
      level: "1"
      controller: "RAID.Slot.5-1"
      physicalDisks:
      - "Disk.Bay.0:Enclosure.Internal.0-1:RAID.Slot.5-1"
      - "Disk.Bay.1:Enclosure.Internal.0-1:RAID.Slot.5-1"
    - name: "VirtualDisk3"
      level: "5"
      sizeGibibytes: 3000
      numberOfPhysicalDisks: 3
      rotational: True
    - name: "VirtualDisk4"
      level: "6"
      sizeGibibytes: 4000
      controller: "RAID.Slot.5-1"
      physicalDisks:
      - "Disk.Bay.0:Enclosure.Internal.0-1:RAID.Slot.5-1"
      - "Disk.Bay.1:Enclosure.Internal.0-1:RAID.Slot.5-1"
      - "Disk.Bay.2:Enclosure.Internal.0-1:RAID.Slot.5-1"
      - "Disk.Bay.3:Enclosure.Internal.0-1:RAID.Slot.5-1"
    - name: "VirtualDisk5"
      level: "1+0"
      sizeGibibytes: 4000
      numberOfPhysicalDisks: 4
    - name: "VirtualDisk6"
      level: "5+0"
      controller: "RAID.Slot.5-1"
      physicalDisks:
      - "Disk.Bay.0:Enclosure.Internal.0-1:RAID.Slot.5-1"
      - "Disk.Bay.1:Enclosure.Internal.0-1:RAID.Slot.5-1"
      - "Disk.Bay.2:Enclosure.Internal.0-1:RAID.Slot.5-1"
      - "Disk.Bay.3:Enclosure.Internal.0-1:RAID.Slot.5-1"
      - "Disk.Bay.4:Enclosure.Internal.0-1:RAID.Slot.5-1"
      - "Disk.Bay.5:Enclosure.Internal.0-1:RAID.Slot.5-1"
    - name: "VirtualDisk7"
      level: "6+0"
      numberOfPhysicalDisks: 8
      sizeGibibytes: 16000
      rotational: False
