apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: image-builder-versions-replacements
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: localhost/replacement-transformer
replacements: []
