apiVersion: builtin
kind: PatchStrategicMergeTransformer
metadata:
  name: smp_cleanup_imported
patches: |-
  ---
  apiVersion: airshipit.org/v1alpha1
  kind: VariableCatalogue
  metadata:
    name: imported-secrets
  $patch: delete
