apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../function/baremetal-operator/v0.5.0
  - ../../../../function/hwcc
  - ../../../../function/clusterctl
  - ../../../../function/ironic-deployment/v0.5.0

commonLabels:
  airshipit.org/stage: initinfra
