# These rules inject passphrases and certificate variable values
# from the `generate-secret-catalogue` into the `generate-passphrases-template`
# and `generate-certificates-template` function's Template plugin configs respectively.
apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  # NOTE: change this when copying this example
  name: generatesecrets-example-replacements
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: quay.io/airshipit/replacement-transformer:latest
replacements:
- source:
    objref:
      # NOTE: change this to match your passphrases's metadata.name
      name: passphrases-example
    fieldref: "{.generate.passphrases}"
  target:
    objref:
      kind: Templater
      name: generate-passphrases-template
    fieldrefs: ["{.values.passphrases}"]
- source:
    objref:
      # NOTE: change this to match your certificates's metadata.name
      name: certificates-example
    fieldref: "{.generate.certificates}"
  target:
    objref:
      kind: Templater
      name: generate-certificates-template
    fieldrefs: ["{.values.certificates}"]
