resources:
  - ../../../../function/baremetal-operator
  - ../../../../function/clusterctl
  - ../../../../function/helm-operator
  - ../../../../composite/infra
  - ../catalogues

commonLabels:
  airshipit.org/stage: initinfra

transformers:
  - ../../../../composite/infra/replacements
  - ../../../../function/baremetal-operator/replacements
  - ../../../../function/helm-operator/replacements
