apiVersion: airshipit.org/v1alpha1
kind: VariableCatalogue
metadata:
  # NOTE: change this when copying this example
  name: passphrases-example
  labels:
    airshipit.org/deploy-k8s: "false"
generate:
  passphrases:
    secret1:
      namespace: ns1
      deployk8s: true
      values:
      - keyName: key1
        generationType: derivePassword
        passwordType: long
        user: test
        site: example.com
        masterPassword: master
        length: 2
      - generationType: randAlpha
        length: 3
      - keyName: key3
        generationType: static
        value: mypass
      - keyName: key4
        generationType: randAlphaNum
        length: 4
      - keyName: key5
        generationType: randNumeric
        length: 5
    secret2:
      namespace: test
      values:
      - generationType: randAscii
        length: 3
      - keyName: key2
        generationType: regexGen
        regex: "[efghul][a-z]{2,3}[0-9]{2,8}"
        limit: 10
