---
apiVersion: airshipit.org/v1alpha1
kind: KubernetesApply
metadata:
  labels:
    airshipit.org/deploy-k8s: "false"
  name: kubernetes-apply
config:
  waitOptions:
    timeout: 2000
  pruneOptions:
    prune: false
---
apiVersion: airshipit.org/v1alpha1
kind: KubernetesApply
metadata:
  labels:
    airshipit.org/deploy-k8s: "false"
  name: kubernetes-apply-controlplane
config:
  waitOptions:
    timeout: 3600
  pruneOptions:
    prune: false
---
# This is added to support phase with no-wait
# When there is a wait, then it does status-check and fails
# if the resource status(condition) is not met.
# There are cases where the resource do not have status
# field implemeneted. So a wait will fail with status check
apiVersion: airshipit.org/v1alpha1
kind: KubernetesApply
metadata:
  labels:
    airshipit.org/deploy-k8s: "false"
  name: kubernetes-apply-nowait
config:
  waitOptions:
    timeout: 0
  pruneOptions:
    prune: false
---
apiVersion: airshipit.org/v1alpha1
kind: Clusterctl
metadata:
  name: clusterctl_move
move-options: {}
action: move
---
apiVersion: airshipit.org/v1alpha1
kind: IsoConfiguration
metadata:
  name: isogen
  labels:
    airshipit.org/deploy-k8s: "false"
builder:
  outputFileName: ephemeral.iso
container:
  containerRuntime: docker
  image: quay.io/airshipit/image-builder:latest-ubuntu_focal
  volume: /srv/images:/config
---
apiVersion: airshipit.org/v1alpha1
kind: GenericContainer
metadata:
  name: encrypter
  labels:
    airshipit.org/deploy-k8s: "false"
spec:
  type: krm
  sinkOutputDir: "target/generator/results/generated"
  image: gcr.io/kpt-fn-contrib/sops:v0.1.0
  envVars:
  - SOPS_IMPORT_PGP
  - SOPS_PGP_FP
config: |
  apiVersion: v1
  kind: ConfigMap
  data:
    cmd: encrypt
    unencrypted-regex: '^(kind|apiVersion|group|metadata)$'
---
# This executor launchs a bootstrap container, which creates
# an Azure Kubernetes Service (AKS) cluster
apiVersion: airshipit.org/v1alpha1
kind: BootConfiguration
metadata:
  name: ephemeral-az-genesis
  labels:
    airshipit.org/deploy-k8s: "false"
ephemeralCluster:
  bootstrapCommand: create
  configFilename: azure-config.yaml
bootstrapContainer:
  containerRuntime: docker
  image: quay.io/airshipit/capz-bootstrap:latest
  volume: /tmp:/kube
  saveKubeconfigFileName: capz.kubeconfig
---
# This executor launchs a bootstrap container, which deletes
# an Azure Kubernetes Service (AKS) cluster
apiVersion: airshipit.org/v1alpha1
kind: BootConfiguration
metadata:
  name: ephemeral-az-cleanup
  labels:
    airshipit.org/deploy-k8s: "false"
ephemeralCluster:
  bootstrapCommand: delete
  configFilename: azure-config.yaml
bootstrapContainer:
  containerRuntime: docker
  image: quay.io/airshipit/capz-bootstrap:latest
  volume: /tmp:/kube
  saveKubeconfigFileName: capz.kubeconfig
---
# This executor launchs a bootstrap container, which creates
# a Google Kubernetes Engine (GKE) cluster
apiVersion: airshipit.org/v1alpha1
kind: BootConfiguration
metadata:
  name: ephemeral-gcp-genesis
  labels:
    airshipit.org/deploy-k8s: "false"
ephemeralCluster:
  bootstrapCommand: create
  configFilename: gcp-config.yaml
bootstrapContainer:
  containerRuntime: docker
  image: quay.io/airshipit/capg-bootstrap:latest
  volume: /tmp:/kube
  saveKubeconfigFileName: capg.kubeconfig
---
# This executor launchs a bootstrap container, which deletes
# a Google Kubernetes Engine (GKE) cluster
apiVersion: airshipit.org/v1alpha1
kind: BootConfiguration
metadata:
  name: ephemeral-gcp-cleanup
  labels:
    airshipit.org/deploy-k8s: "false"
ephemeralCluster:
  bootstrapCommand: delete
  configFilename: gcp-config.yaml
bootstrapContainer:
  containerRuntime: docker
  image: quay.io/airshipit/capg-bootstrap:latest
  volume: /tmp:/kube
  saveKubeconfigFileName: capg.kubeconfig
---
# This executor launchs a bootstrap container, which creates
# an ephemeral K8S cluster in Openstack
apiVersion: airshipit.org/v1alpha1
kind: BootConfiguration
metadata:
  name: ephemeral-os-genesis
  labels:
    airshipit.org/deploy-k8s: "false"
ephemeralCluster:
  bootstrapCommand: create
  configFilename: openstack-config.yaml
bootstrapContainer:
  containerRuntime: docker
  image: quay.io/airshipit/capo-ephemeral:latest
  volume: /tmp:/kube
  saveKubeconfigFileName: capo.kubeconfig
---
# This executor launchs a bootstrap container, which deletes
# ephemeral K8S cluster in Openstack
apiVersion: airshipit.org/v1alpha1
kind: BootConfiguration
metadata:
  name: ephemeral-os-cleanup
  labels:
    airshipit.org/deploy-k8s: "false"
ephemeralCluster:
  bootstrapCommand: delete
  configFilename: openstack-config.yaml
bootstrapContainer:
  containerRuntime: docker
  image: quay.io/airshipit/capo-ephemeral:latest
  volume: /tmp:/kube
  saveKubeconfigFileName: capo.kubeconfig
---
apiVersion: airshipit.org/v1alpha1
kind: BaremetalManager
metadata:
  name: RemoteDirectEphemeral
  labels:
    airshipit.org/deploy-k8s: "false"
spec:
  operation: remote-direct
  hostSelector:
    name: REPLACE_ME
  operationOptions:
    remoteDirect:
      isoURL: REPLACE_ME
---
