resources:
  - phases.yaml
  - plan.yaml
  - executors.yaml
  - cluster-map.yaml
  - kubeconfig.yaml
  - ../function/clusterctl
  - ../function/airshipctl-base-catalogues
patchesStrategicMerge:
  - clusterctl_init_options.yaml
transformers:
  - ../function/clusterctl/replacements
