apiVersion: airshipit.org/v1alpha1
kind: PhasePlan
metadata:
  name: phasePlan
description: "Default phase plan"
phases:
  - name: initinfra-ephemeral
  - name: initinfra-networking-ephemeral
  - name: clusterctl-init-ephemeral
  - name: controlplane-ephemeral
  - name: clusterctl-init-target
  - name: initinfra-target
  - name: initinfra-networking-target
  - name: workers-target
  - name: workers-classification
  - name: workload-target
