apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: generate-secret-replacements
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: quay.io/airshipit/replacement-transformer:latest
replacements:
- source:
    objref:
      name: generate-secret-catalogue
    fieldref: "{.generate.passphrases}"
  target:
    objref:
      kind: Templater
      name: generate-passphrases-template
    fieldrefs: ["{.values.passphrases}"]
- source:
    objref:
      name: generate-secret-catalogue
    fieldref: "{.generate.certificates}"
  target:
    objref:
      kind: Templater
      name: generate-certificates-template
    fieldrefs: ["{.values.certificates}"]
