# These rules inject versioned artifacts into the clusterctl function.
apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: k8scontrol-versions-replacements
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: quay.io/airshipit/replacement-transformer:latest
replacements:
# Replace capm3 versions
- source:
    objref:
      kind: VariableCatalogue
      name: versions-airshipctl
    fieldref: "{.images.capm3.manager}"
  target:
    objref:
      kind: Clusterctl
      name: clusterctl_init
    fieldrefs: ["{.additional-vars.CONTAINER_CAPM3_MANAGER}"]
- source:
    objref:
      kind: VariableCatalogue
      name: versions-airshipctl
    fieldref: "{.images.capm3.auth_proxy}"
  target:
    objref:
      kind: Clusterctl
      name: clusterctl_init
    fieldrefs: ["{.additional-vars.CONTAINER_CAPM3_AUTH_PROXY}"]
# Replace cacpk versions
- source:
    objref:
      kind: VariableCatalogue
      name: versions-airshipctl
    fieldref: "{.images.cacpk.manager}"
  target:
    objref:
      kind: Clusterctl
      name: clusterctl_init
    fieldrefs: ["{.additional-vars.CONTAINER_CACPK_MANAGER}"]
- source:
    objref:
      kind: VariableCatalogue
      name: versions-airshipctl
    fieldref: "{.images.cacpk.auth_proxy}"
  target:
    objref:
      kind: Clusterctl
      name: clusterctl_init
    fieldrefs: ["{.additional-vars.CONTAINER_CACPK_AUTH_PROXY}"]
# Replace cabpk versions
- source:
    objref:
      kind: VariableCatalogue
      name: versions-airshipctl
    fieldref: "{.images.cabpk.manager}"
  target:
    objref:
      kind: Clusterctl
      name: clusterctl_init
    fieldrefs: ["{.additional-vars.CONTAINER_CABPK_MANAGER}"]
- source:
    objref:
      kind: VariableCatalogue
      name: versions-airshipctl
    fieldref: "{.images.cabpk.auth_proxy}"
  target:
    objref:
      kind: Clusterctl
      name: clusterctl_init
    fieldrefs: ["{.additional-vars.CONTAINER_CABPK_AUTH_PROXY}"]
# Replace capd versions
- source:
    objref:
      kind: VariableCatalogue
      name: versions-airshipctl
    fieldref: "{.images.capd.manager}"
  target:
    objref:
      kind: Clusterctl
      name: clusterctl_init
    fieldrefs: ["{.additional-vars.CONTAINER_CAPD_MANAGER}"]
- source:
    objref:
      kind: VariableCatalogue
      name: versions-airshipctl
    fieldref: "{.images.capd.auth_proxy}"
  target:
    objref:
      kind: Clusterctl
      name: clusterctl_init
    fieldrefs: ["{.additional-vars.CONTAINER_CAPD_AUTH_PROXY}"]
# Replace capi versions
- source:
    objref:
      kind: VariableCatalogue
      name: versions-airshipctl
    fieldref: "{.images.capi.manager}"
  target:
    objref:
      kind: Clusterctl
      name: clusterctl_init
    fieldrefs: ["{.additional-vars.CONTAINER_CAPI_MANAGER}"]
- source:
    objref:
      kind: VariableCatalogue
      name: versions-airshipctl
    fieldref: "{.images.capi.auth_proxy}"
  target:
    objref:
      kind: Clusterctl
      name: clusterctl_init
    fieldrefs: ["{.additional-vars.CONTAINER_CAPI_AUTH_PROXY}"]

