apiVersion: airshipit.org/v1alpha1
kind: PhasePlan
metadata:
  name: phasePlan
phaseGroups:
  - name: group1
    phases:
      - name: clusterctl-init-ephemeral
      - name: controlplane-ephemeral
      - name: initinfra-target
      - name: clusterctl-init-target
      - name: clusterctl-move
      - name: workers-target
---
apiVersion: airshipit.org/v1alpha1
kind: Clusterctl
metadata:
  name: clusterctl_init
env-vars: true
