apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: helm-repository-versions-replacements
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: quay.io/airshipit/replacement-transformer:v2
replacements:
- source:
    objref:
      kind: VersionsCatalogue
      name: versions-airshipctl
    fieldref: "{.spec.helm_repositories.helm_chart_collator.url}"
  target:
    objref:
      kind: HelmRepository
      name: collator
    fieldrefs: ["{.spec.url}"]
