---
apiVersion: "helm.fluxcd.io/v1"
kind: HelmRelease
metadata:
  name: ingress
spec:
  wait: true
  timeout: 600
  # This chart doesn't have any helm tests, but this still runs a noop
  # helm test flow, to ensure we can do this.
  test:
    enable: true
  values:
    defaultBackend:
      enabled: true
    controller:
      service:
        type: NodePort
        nodePorts:
          http: 30000
          https: 30001
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 3.5.1
