apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: generated-secrets-replacements
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: quay.io/airshipit/replacement-transformer:latest
replacements:
- source:
    objref:
      name: generated-secrets
    fieldref: "{.isoImage.passwords.root}"
  target:
    objref:
      kind: Secret
      name: ephemeral-bmc-secret
    fieldrefs: ["stringData.userData%REPLACEMENT_ISO_PASSWORD_ROOT%"]
- source:
    objref:
      name: generated-secrets
    fieldref: "{.isoImage.passwords.deployer}"
  target:
    objref:
      kind: Secret
      name: ephemeral-bmc-secret
    fieldrefs: ["stringData.userData%REPLACEMENT_ISO_PASSWORD_DEPLOYER%"]
