# These rules inject networking info artifacts into the ephemeral function.
apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: ephemeral-networking-replacements
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: localhost/replacement-transformer
replacements:
# Substring-replace the ephemeral control plane's info
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.kubernetes.controlPlaneEndpoint.host
  target:
    objref:
      name: ephemeral-bmc-secret
      kind: Secret
    fieldrefs: ["stringData.userData%REPLACEMENT_CP_IP%"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.kubernetes.controlPlaneEndpoint.port
  target:
    objref:
      name: ephemeral-bmc-secret
      kind: Secret
    fieldrefs: ["stringData.userData%REPLACEMENT_CP_PORT%"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.kubernetes.apiserverCertSANs
  target:
    objref:
      name: ephemeral-bmc-secret
      kind: Secret
    fieldrefs: ["stringData.userData%REPLACEMENT_CERT_SANS%"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.kubernetes.podCidr
  target:
    objref:
      name: ephemeral-bmc-secret
      kind: Secret
    fieldrefs: ["stringData.userData%REPLACEMENT_POD_CIDR%"]
# Replace the k8s controlplane NTP servers
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.ntp.servers[0]
  target:
    objref:
      name: ephemeral-bmc-secret
      kind: Secret
    fieldrefs: ["stringData.userData%REPLACEMENT_NTP_SERVER1%"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.ntp.servers[1]
  target:
    objref:
      name: ephemeral-bmc-secret
      kind: Secret
    fieldrefs: ["stringData.userData%REPLACEMENT_NTP_SERVER2%"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.ntp.servers[2]
  target:
    objref:
      name: ephemeral-bmc-secret
      kind: Secret
    fieldrefs: ["stringData.userData%REPLACEMENT_NTP_SERVER3%"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.ntp.servers[3]
  target:
    objref:
      name: ephemeral-bmc-secret
      kind: Secret
    fieldrefs: ["stringData.userData%REPLACEMENT_NTP_SERVER4%"]
