apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: k8scontrol-cluster-replacements
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: localhost/replacement-transformer
replacements:
# Target Cluster - Azure K8S Version
- source:
    objref:
      kind: VersionsCatalogue
      name: versions-airshipctl
    fieldref: "{.spec.kubernetes}"
  target:
    objref:
      kind: MachineDeployment
      name: target-cluster-md-0
    fieldrefs: ["{.spec.template.spec.version}"]

# Target Cluster - Worker Replica Count
- source:
    objref:
      kind: VariableCatalogue
      name: azure-catalogue
    fieldref: "{.worker.replicas}"
  target:
    objref:
      kind: MachineDeployment
      name: target-cluster-md-0
    fieldrefs: ["{.spec.replicas}"]

# Target Cluster - Worker VM Flavor
- source:
    objref:
      kind: VariableCatalogue
      name: azure-catalogue
    fieldref: "{.controlplane.vmSize}"
  target:
    objref:
      kind: AzureMachineTemplate
      name: target-cluster-md-0
    fieldrefs: ["{.spec.template.spec.vmSize}"]

# Target Cluster - Control Plane SSH Public Key access
- source:
    objref:
      kind: VariableCatalogue
      name: azure-catalogue
    fieldref: "{.controlplane.sshPublicKey}"
  target:
    objref:
      kind: AzureMachineTemplate
      name: target-cluster-md-0
    fieldrefs: ["{.spec.template.spec.sshPublicKey}"]
