apiVersion: airshipit.org/v1alpha1
kind: IsoConfiguration
metadata:
  name: isogen
  labels:
    airshipit.org/deploy-k8s: "false"
builder:
  userDataSelector:
    kind: Secret
    labelSelector: airshipit.org/ephemeral-user-data
  userDataKey: userData
  networkConfigSelector:
    kind: BareMetalHost
    labelSelector: airshipit.org/ephemeral-node
  networkConfigKey: networkData
  outputFileName: ephemeral.iso
container:
  containerRuntime: docker
  image: quay.io/airshipit/image-builder:latest-ubuntu_focal
  volume: /srv/images:/config
