apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../catalogues
  - ../../../../type/gating/target/workers
  - nodes

namespace: target-infra

transformers:
  - ../../../../type/gating/target/workers/replacements
