apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: workers-networking-replacements
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: quay.io/airshipit/replacement-transformer:latest
replacements:
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.ntp
  target:
    objref:
      kind: KubeadmConfigTemplate
      name: worker-1
    fieldrefs: ["spec.template.spec.ntp"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.ntp.servers[0]
  target:
    objref:
      kind: KubeadmConfigTemplate
      name: worker-1
    fieldrefs: ["spec.template.spec.files[*].content%REPLACEMENT_NTP_SERVER1%"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.ntp.servers[1]
  target:
    objref:
      kind: KubeadmConfigTemplate
      name: worker-1
    fieldrefs: ["spec.template.spec.files[*].content%REPLACEMENT_NTP_SERVER2%"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.ntp.servers[2]
  target:
    objref:
      kind: KubeadmConfigTemplate
      name: worker-1
    fieldrefs: ["spec.template.spec.files[*].content%REPLACEMENT_NTP_SERVER3%"]
- source:
    objref:
      kind: NetworkCatalogue
      name: networking
    fieldref: spec.ntp.servers[3]
  target:
    objref:
      kind: KubeadmConfigTemplate
      name: worker-1
    fieldrefs: ["spec.template.spec.files[*].content%REPLACEMENT_NTP_SERVER4%"]