apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # TODO (dukov) It's recocommended to upload BareMetalHost objects separately
  # otherwise nodes will hang in 'registering' state for quite a long time
  - nodes
  - ../../../../function/airshipctl-catalogues
  - ../../../../function/k8scontrol

patchesStrategicMerge:
  - versions-catalogue-patch.yaml

transformers:
  - ../../../../function/k8scontrol/replacements
