apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # TODO (dukov) It's recocommended to upload BareMetalHost objects separately
  # otherwise nodes will hang in 'registering' state for quite a long time
  - ../../../../type/gating/ephemeral/controlplane
  - ../../target/catalogues # NOTE: use target networking for this phase
  - nodes

namespace: target-infra

transformers:
  - ../../../../type/gating/ephemeral/controlplane/replacements

patchesJson6902:
  - target:
      group: controlplane.cluster.x-k8s.io
      version: v1alpha4
      kind: KubeadmControlPlane
      name: cluster-controlplane
    path: patch_json6902_controlplane.yaml

patchesStrategicMerge:
  - versions-airshipctl.yaml
