apiVersion: airshipit.org/v1alpha1
kind: Clusterctl
metadata:
  labels:
    airshipit.org/deploy-k8s: "false"
  name: clusterctl_init
init-options:
  core-provider: "cluster-api:v0.4.2"
  bootstrap-providers: "kubeadm:v0.4.2"
  infrastructure-providers: "metal3:v0.5.0"
  control-plane-providers: "kubeadm:v0.4.2"
providers:
  - name: "metal3"
    type: "InfrastructureProvider"
    url: airshipctl/manifests/function/capm3/v0.5.0
  - name: "kubeadm"
    type: "BootstrapProvider"
    url: airshipctl/manifests/function/cabpk/v0.4.2
  - name: "cluster-api"
    type: "CoreProvider"
    url: airshipctl/manifests/function/capi/v0.4.2
  - name: "kubeadm"
    type: "ControlPlaneProvider"
    url: airshipctl/manifests/function/cacpk/v0.4.2

# The default image repository and tag for a specific component
# can be overriden here
images:
  cert-manager:
    repository: "quay.io/jetstack"
  cluster-api/cluster-api-controller:
    repository: "gcr.io/k8s-staging-cluster-api"
    tag: "v0.4.2"
  bootstrap-kubeadm/kubeadm-bootstrap-controller:
    repository: "gcr.io/k8s-staging-cluster-api"
    tag: "v0.4.2"
  control-plane-kubeadm/kubeadm-control-plane-controller:
    repository: "gcr.io/k8s-staging-cluster-api"
    tag: "v0.4.2"
  infrastructure-metal3/cluster-api-provider-metal3:
    repository: "quay.io/metal3-io"
    tag: "v0.5.0"
  infrastructure-metal3/kube-rbac-proxy:
    repository: "gcr.io/kubebuilder"
    tag: "v0.8.0"
  infrastructure-docker/capd-manager:
    repository: "gcr.io/k8s-staging-cluster-api"
    tag: "v20201019-v0.3.10-86-gc1647481f"
  infrastructure-docker/kube-rbac-proxy:
    repository: "gcr.io/kubebuilder"
    tag: "v0.4.0"
  infrastructure-azure/cluster-api-azure-controller:
    repository: "gcr.io/k8s-staging-cluster-api-azure"
    tag: "v0.4.9"
  infrastructure-azure/kube-rbac-proxy:
    repository: "gcr.io/kubebuilder"
    tag: "v0.4.1"
  infrastructure-gcp/cluster-api-gcp-controller:
    repository: "gcr.io/k8s-staging-cluster-api-gcp"
    tag: "master"
  infrastructure-gcp/kube-rbac-proxy:
    repository: "gcr.io/kubebuilder"
    tag: "v0.4.1"
  infrastructure-openstack/capi-openstack-controller-amd64:
    repository: "gcr.io/k8s-staging-capi-openstack"
    tag: "v20200707-v0.3.1"
  infrastructure-openstack/kube-rbac-proxy:
    repository: "gcr.io/kubebuilder"
    tag: "v0.4.1"


# These default images can be overridden via the `replacements/` entrypoint
additional-vars: {}
