apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: helm-operator-versions-replacements
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: quay.io/airshipit/replacement-transformer:dev
replacements:
- source:
    objref:
      kind: VariableCatalogue
      name: versions-airshipctl
    fieldref: images.helm_operator.helm_operator.helm_operator
  target:
    objref:
      kind: Deployment
      name: helm-operator
    fieldrefs: ["spec.template.spec.containers[name=helm-operator].image"]

