kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
metadata:
  name: cluster-controlplane
spec:
  replicas: 1
  version: v1.18.6
  infrastructureTemplate:
    kind: Metal3MachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
    name: cluster-controlplane
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        timeoutForControlPlane: 1000s
    files:
      - path: "/etc/systemd/system/containerd.service.d/http-proxy.conf"
        content: |
          [Service]
          Environment="HTTP_PROXY=REPLACEMENT_HTTP_PROXY"
          Environment="HTTPS_PROXY=REPLACEMENT_HTTPS_PROXY"
          Environment="NO_PROXY=REPLACEMENT_NO_PROXY"
      # Since we are using containerd as a default CRI, we do not need
      # any adjustments and settings for docker anymore. However, if for
      # some reason docker has to be presented in the system, we need to
      # create http-proxy.conf.
      - path: "/etc/chrony/chrony.conf"
        content: |
          # This directive specify the location of the file containing ID/key pairs for
          # NTP authentication.
          keyfile /etc/chrony/chrony.keys

          # This directive specify the file into which chronyd will store the rate
          # information.
          driftfile /var/lib/chrony/chrony.drift

          # Uncomment the following line to turn logging on.
          #log tracking measurements statistics

          # Log files location.
          logdir /var/log/chrony

          # Stop bad estimates upsetting machine clock.
          maxupdateskew 100.0

          # This directive enables kernel synchronisation (every 11 minutes) of the
          # real-time clock. Note that it can&#226;&#8364;™t be used along with the 'rtcfile' directive.
          rtcsync

          # Step the system clock instead of slewing it if the adjustment is larger than
          # one second, but only in the first three clock updates.
          makestep 1 3

          server REPLACEMENT_NTP_SERVER1 iburst
          server REPLACEMENT_NTP_SERVER2 iburst
          server REPLACEMENT_NTP_SERVER3 iburst
          server REPLACEMENT_NTP_SERVER4 iburst

          #Enable Chrony to operate as an NTP server for local applications e.g. Prometheus.
          allow 127.0.0.0/8
    # TODO: add download sources to the versions catalogue
    preKubeadmCommands:
      # Restart docker to apply any proxy settings
      - export HOME=/root
      - mkdir -p /etc/containerd
      - containerd config default | sed -r -e '/\[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc\]$/a\          SystemdCgroup = true' | tee /etc/containerd/config.toml
      - systemctl daemon-reload
      - systemctl restart containerd
      - systemctl restart chrony.service
      - systemctl is-active --quiet chrony.service && echo "Chrony service was restarted!"
    initConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data.local_hostname }}'
        kubeletExtraArgs:
          node-labels: 'metal3.io/uuid={{ ds.meta_data.uuid }},node-type=controlplane'
          cgroup-driver: "systemd"
          container-runtime: remote
        criSocket: "unix:///run/containerd/containerd.sock"
    joinConfiguration:
      controlPlane: {}
      nodeRegistration:
        name: '{{ ds.meta_data.local_hostname }}'
        kubeletExtraArgs:
          node-labels: 'metal3.io/uuid={{ ds.meta_data.uuid }},node-type=controlplane'
          cgroup-driver: "systemd"
          container-runtime: remote
        criSocket: "unix:///run/containerd/containerd.sock"

    users:
    - name: deployer
      sshAuthorizedKeys:
      - REPLACE_HOST_SSH_KEY
      sudo: ALL=(ALL) NOPASSWD:ALL
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: Metal3MachineTemplate
metadata:
  name: cluster-controlplane
spec:
  template:
    spec:
      image:
        # NOTE (dukov) this should be overridden on lower levels
        url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
        checksum: 2c890254ecbd4e6b4931f864ef72b337
      hostSelector:
        matchLabels:
          airshipit.org/k8s-role: controlplane-host
