apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../function/k8scontrol-capz/v0.5.2
  - ../../target/catalogues

namespace: target-infra

patchesStrategicMerge:
  - azure-cluster-identity.yaml
  - azure-subnet-settings.yaml

transformers:
  - ../../../../function/k8scontrol-capz/v0.5.2/replacements
