# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: release-github

# Runs on airshipctl non-pre-releases
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download release notes utility
        run: |
          sudo npm install github-release-notes@0.17.1 -g
      - name: Generate release notes
        run: |
          TAG_NAME=${TAG##*/}
          gren changelog --override --generate \
            --username airshipit --repo airshipctl \
            --changelog-filename release-notes.md \
            --token "$GITHUB_TOKEN" \
            --tags "$TAG_NAME" \
            --data-source milestones \
            --milestone-match '{{tag_name}}' \
            --debug
          cat release-notes.md
        env:
          TAG: ${{ github.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.x
      - name: Generate binaries and create github release
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          commit: currentcommit
          date: builddate
          args: release --release-notes=release-notes.md --skip-validate --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
