# Helm Charts from Helm Repository (Helm Collator)
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: helm-repo
spec:
  interval: 5m
  url: http://helm-chart-collator.collator.svc:8080